import type { Metadata } from "next";
import { Jost, Oswald } from "next/font/google";
import "./globals.css";
import HeaderClient from "@/components/common/headers";
// import Footer from "@/components/common/footer";
import PageScrollWrapper from "@/components/common/wrappers/pageScrollWrapper";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jost.variable} ${oswald.variable} antialiased`}>
        <HeaderClient />
        <PageScrollWrapper>{children}</PageScrollWrapper>
      </body>
    </html>
  );
}
